### ISSUE TITLE
incorrectly brings along list items when copying

### ISSUE THREAD

**Issue by garretwilson** [therealglazou/bluegriffon#14]
If I have a list of links:

````html
<ul>
  <li><a href="http://example.com/foo"><code>foo</code></a></li>
  <li><a href="http://example.com/bar"><code>bar</code></a></li>
</ul>
````

In the WYSIWYG view, if I use the `Esc` key to select only the `<a href="http://example.com/foo"><code>foo</code></a>` and copy that element, if I paste it inside a paragraph I should get this:

````html
<p>blah blah <a href="http://example.com/foo"><code>foo</code></a> blah blah</p>
````

But instead I get this:

````html
<p>blah blah </p>
<ul>
  <li><a href="http://example.com/foo"><code>foo</code></a></li>
</ul>
<p> blah blah</p>
````

I told BG very carefully that I only wanted to copy `<a href="http://example.com/foo"><code>foo</code></a>`, so bringing along the entire list item is a bug.

**Comment by therealglazou** [comment]
Confirming. Gecko's document encoder was promoting selection ranges in `nsHTMLCopyEncoder::SetSelection`. I am going to disable this, but only dogfooding will tell if it is entirely safe.

**Comment by therealglazou** [comment]
https://github.com/therealglazou/bluegriffon/commit/62c51792aeaaadd5bc3805b6ca9bb3db13e391a3
