### ISSUE TITLE
Provide build instructions using git rather than hg

### ISSUE THREAD

**Issue by probonopd** [therealglazou/bluegriffon#17]
I am trying to do continuous builds using Travis CI in the cloud. For this, I want the build process to download to produce only the minimal amount of traffic possible and the build to be as fast as possible. Right now, in `bluegriffon/raw/bg2/config/mozilla_central_revision.txt` the hg revision is stored which means that I need to use mercurial which happens to be slow. Would it be possible to provide the git commit instead? That would allow me to `git clone https://github.com/mozilla/gecko-dev` which might significantly speed up the build process.

**Comment by therealglazou** [comment]
This is now done. See https://github.com/therealglazou/bluegriffon/blob/master/README.md
