### ISSUE TITLE
"Open with" no longer works with BlueGriffon 2.0 on Windows

### ISSUE THREAD

**Issue by garretwilson** [therealglazou/bluegriffon#18]
In the Windows 10 File Explorer I can no longer right-click on an e.g. XHTML file and then select "Open with" and select BlueGriffon to open a file in BP. In BG 1.8, this would bring up BG and then load the indicated file. In BG 2.0 it simple brings up BG, but does not load the file.

This is a significant setback as it alters my main workflow.

**Comment by therealglazou** [comment]
Fixed by 3.0.1
