### ISSUE TITLE
Bluegriffon doesn't Reloads if file saved on any other editor

### ISSUE THREAD

**Issue by IamManchanda** [therealglazou/bluegriffon#19]
I Felt that a best mate to sublime text can be blue griffon but found out that if i save a file in sublime text , blue griffon neither reloads the page nor does it provide any option to reload the page which i feel is a big bug which if sorted can make thing life easier .
Please resolve this issue 

![bug-bg_1](https://cloud.githubusercontent.com/assets/4970624/15800150/bbcaf8ca-2a8f-11e6-9bf4-ca6e75092ebf.png)
![bug-bg_2](https://cloud.githubusercontent.com/assets/4970624/15800151/bbcecfb8-2a8f-11e6-923e-344775f394e5.png)

**Comment by therealglazou** [comment]
Yes it does, but only from the Wysiwyg view at this time. If you modify a document outside of BlueGriffon, come back to BlueGriffon's window and change the caret's position, it works. I'll make sure to have that option in the Souce View too in the future
