### ISSUE TITLE
problem compiling bg2

### ISSUE THREAD

**Issue by SolarAquarion** [therealglazou/bluegriffon#2]
0:13.17 Reticulating splines...
 0:15.67 Traceback (most recent call last):
 0:15.67   File "./config.status", line 982, in <module>
 0:15.67     config_status(**args)
 0:15.68   File "/home/solaraquarion/bluegriffon/src/mozilla-central/python/mozbuild/mozbuild/config_status.py", line 149, in config_status
 0:15.68     summary = the_backend.consume(definitions)
 0:15.68   File "/home/solaraquarion/bluegriffon/src/mozilla-central/python/mozbuild/mozbuild/backend/base.py", line 180, in consume
 0:15.68     for obj in objs:
 0:15.68   File "/home/solaraquarion/bluegriffon/src/mozilla-central/python/mozbuild/mozbuild/frontend/emitter.py", line 140, in emit
 0:15.68     for out in output:
 0:15.68   File "/home/solaraquarion/bluegriffon/src/mozilla-central/python/mozbuild/mozbuild/frontend/reader.py", line 975, in read_mozbuild
 0:15.68     raise bre
 0:15.68 mozbuild.frontend.reader.BuildReaderError:
 0:15.68 ==============================
 0:15.68 ERROR PROCESSING MOZBUILD FILE
 0:15.68 ==============================
 0:15.68 
 0:15.68 The error occurred while processing the following file:
 0:15.68 
 0:15.68     /home/solaraquarion/bluegriffon/src/mozilla-central/bluegriffon/components/moz.build
 0:15.68 
 0:15.68 The underlying problem is we referenced a path that does not exist. That path is:
 0:15.68 
 0:15.68     /home/solaraquarion/bluegriffon/src/mozilla-central/bluegriffon/components/devtools/moz.build
 0:15.68 
 0:15.68 Either create the file if it needs to exist or do not reference it.
 0:15.68 
 0:15.77 *** Fix above errors and then restart with\
 0:15.77                "/usr/bin/make -f client.mk build"
 0:15.77 /home/solaraquarion/bluegriffon/src/mozilla-central/client.mk:363: recipe for target 'configure' failed
 0:15.77 make[2]: *** [configure] Error 1
 0:15.77 /home/solaraquarion/bluegriffon/src/mozilla-central/client.mk:377: recipe for target '/home/solaraquarion/bluegriffon/src/mozilla-central/obj-x86_64-unknown-linux-gnu/Makefile' failed
 0:15.77 make[1]: *** [/home/solaraquarion/bluegriffon/src/mozilla-central/obj-x86_64-unknown-linux-gnu/Makefile] Error 2
 0:15.77 client.mk:171: recipe for target 'build' failed
 0:15.77 make: *** [build] Error 2
 0:15.77 0 compiler warnings present.
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by therealglazou** [comment]
Fixed, thanks for the heads up, this was not meant to be pushed to the branch.
