### ISSUE TITLE
Menubar not visible

### ISSUE THREAD

**Issue by RFCanon** [therealglazou/bluegriffon#20]
Menubar is not visible in Windows 7 Pro (64-bit).  See below:

![image](https://cloud.githubusercontent.com/assets/4671859/15802688/38e69f5e-2a80-11e6-8ab1-7bebc5dca807.png)

Even when selected:

![image](https://cloud.githubusercontent.com/assets/4671859/15802694/5f248fc8-2a80-11e6-94d9-1dd7e56020c0.png)

**Comment by therealglazou** [comment]
Can you please test again with curent v2.2? If the issue is fixed, please close the issue? Thanks.

**Comment by therealglazou** [comment]
Unable to reproduce with 2.2 and 2.3 RCs. Closing
