### ISSUE TITLE
When I select [Table Properties...], dummy window is opened (foo TD) on Ubuntu 16.04x64 BG 2.1.1.

### ISSUE THREAD

**Issue by lamsh** [therealglazou/bluegriffon#21]
OS: Ubuntu 16.04 64bit
Version: BlueGriffon 2.1.1

When I select [Table Properties...], dummy window is opened (foo TD). Is it bug?

Procedure:
1. Open new page.
2. Insert table.
3. Select table.
4. Select [Table] > [Table Properties...]

![selection_013](https://cloud.githubusercontent.com/assets/3889982/16523251/5f7dda02-3fdd-11e6-977e-74dd2b3b626a.jpg)

![foo_014](https://cloud.githubusercontent.com/assets/3889982/16523266/7a7687fa-3fdd-11e6-9362-3a98baba20ca.jpg)

**Comment by therealglazou** [comment]
Confirmed. Will remove it for 2.2. Thanks a lot.

**Comment by therealglazou** [comment]
Fixed :-)
