### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by Poncho09** [therealglazou/bluegriffon#24]
Hi,

My name is Alfonso Hernandez CEO of Astian Foundation, Astian is a organization dedicated to the development of free software and technologies, As you know the Mozilla Foundation discontinued the development of the operating system Firefox OS, due to this measure, we have made a fork of all this project, including the marketplace and many other subprojects. Bluegriffon is a great project that is based on the core of Firefox and we would like to establish an alliance with its parent company developer.

Thanks for you atention.

**Comment by therealglazou** [comment]
Hi. Can you please explain "establish alliance"? Thank you.
Daniel

**Comment by Poncho09** [comment]
Can we talk via Skype?

**Comment by Poncho09** [comment]
Thanks @therealglazou
