### ISSUE TITLE
ctrl+s hotkey

### ISSUE THREAD

**Issue by alexkmbk** [therealglazou/bluegriffon#25]
There is no ctrl+s hotkey to save current document, that would be nice to have the one (OS Windows).

**Comment by therealglazou** [comment]
Er, sorry, there *is* a ctrl-s hotkey on Windows and it does work. I have just performed a fresh install of 2.2 on a fresh W10 and it does work. Are you using en-US locale or another one? In that case, that would be a l10n issue only.

**Comment by alexkmbk** [comment]
@therealglazou Thanks for reply, I have Win10 Russian Edition, in bluegriffon v2.2 ctrl-s hotkey still doesn't work.

**Comment by therealglazou** [comment]
ah, the translator in russian forgot to set the keys. Can you please let me know what are the standard shortcuts in russian for:  Save, Quit, Close Window, Open, Undo, Redo, Cut, Copy, Paste ? Thanks.

**Comment by alexkmbk** [comment]
Actually, even in the english layout it doesn't work for me, but anyway, if I get you right there is an accordance table (ctrl+english char = ctrl+cyrillic char (in low case) = ctrl + unicode cyrillic code):
Save: ctrl+s =  ctrl+ы =  ctrl+044B
Quit: ctrl+q =  ctrl+й =  ctrl+0439
Close Window: ctrl+w =  ctrl+ц =  ctrl+0446
Open: ctrl+o =  ctrl+щ =  ctrl+0449
Undo: ctrl+z =  ctrl+я =  ctrl+044F
Redo: ctrl+y =  ctrl+н =  ctrl+043D
Cut: ctrl+x =  ctrl+ч =  ctrl+0447
Copy: ctrl+c =  ctrl+с =  ctrl+0441 
Paste: ctrl+v =  ctrl+м =  ctrl+043C

**Comment by therealglazou** [comment]
Thank you @alexkmbk ! I'll try it and will commit the change if it works.

**Comment by therealglazou** [comment]
Fixed by https://github.com/therealglazou/bluegriffon/commit/90af8b2d433b24c896961aff2de094945e2f5b5d
