### ISSUE TITLE
2.1.2 and 2.2 uninstallers confused on Windows

### ISSUE THREAD

**Issue by garretwilson** [therealglazou/bluegriffon#28]
On Windows 10 I installed version 2.2 over version 2.1.2. A few days later I noticed that the list of installed programs for the system contained BlueGriffon 2.1.2 and BlueGriffon 2.2, so I clicked on "uninstall" for BlueGriffon 2.1.2.

Now only BlueGriffon 2.2 shows up in my list of installed programs, but I no longer have "Open with BlueGriffon" in my Windows Explorer context menu for HTML files. Moreover BlueGriffon is not on my start menu. And `C:\Program Files (x86)\BlueGriffon` has a few folders but most of them are empty.

I clicked on "uninstall" for BlueGriffon 2.2 and it said it uninstalled something.

I guess I'm going back to BlueGriffon 2.1.2 until this gets straightened out --- along with the formatting problems in Bug #26.

**Comment by therealglazou** [comment]
We're at 2.3.1. Closing.
