### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [therealglazou/bluegriffon#3]
18:26.26 ../../build/unix/gold/ld: error: hidden symbol 'FT_Get_X11_Font_Format' is not defined locally
18:26.26 collect2: error: ld returned 1 exit status
18:26.26 /home/solaraquarion/bluegriffon/src/mozilla-central/config/rules.mk:808: recipe for target 'libxul.so' failed
18:26.26 make[5]: *** [libxul.so] Error 1
18:26.26 /home/solaraquarion/bluegriffon/src/mozilla-central/config/recurse.mk:70: recipe for target 'toolkit/library/target' failed
18:26.26 make[4]: *** [toolkit/library/target] Error 2
18:26.26 /home/solaraquarion/bluegriffon/src/mozilla-central/config/recurse.mk:32: recipe for target 'compile' failed

**Comment by therealglazou** [comment]
What's the platform? Linux? If you're trying to build the bg2 branch, that's norma, I'm focusing on OSX now and the windows and linux builds of that branch don't work

**Comment by therealglazou** [comment]
closing because nothing I can do w/o description

**Comment by SolarAquarion** [comment]
0:10.63 checking for NSPR - version >= 4.10.8... yes
 0:10.66 configure: error: system NSPR does not support PR_STATIC_ASSERT or including prtypes.h does not provide it
 0:10.66 ------ config.log ------
 0:10.66 typedef __off_t off_t;
 0:10.66                 ^
 0:10.66 ./confdefs.h:11:15: note: expanded from macro 'off_t'
 0:10.66 #define off_t long
 0:10.66               ^
 0:10.66 In file included from configure:14820:
 0:10.66 In file included from /usr/include/nspr/prtypes.h:574:
 0:10.66 In file included from /usr/include/nspr/obsolete/protypes.h:47:
 0:10.66 /usr/include/sys/types.h:98:17: error: cannot combine with previous 'type-name' declaration specifier
 0:10.66 typedef __pid_t pid_t;
 0:10.66                 ^
 0:10.66 ./confdefs.h:12:15: note: expanded from macro 'pid_t'
 0:10.66 #define pid_t int
 0:10.66               ^
 0:10.66 3 errors generated.
 0:10.66 configure: failed program was:
 0:10.66 #line 14819 "configure"
 0:10.66 #include "confdefs.h"
 0:10.66 #include "prtypes.h"
 0:10.66 int main() {
 0:10.66 #ifndef PR_STATIC_ASSERT
 0:10.66                  #error PR_STATIC_ASSERT not defined or requires including prtypes.h
 0:10.66                  #endif
 0:10.66 ; return 0; }
 0:10.66 configure: error: system NSPR does not support PR_STATIC_ASSERT or including prtypes.h does not provide it
 0:10.66 *** Fix above errors and then restart with\
 0:10.66                "/usr/bin/make -f client.mk build"
 0:10.66 /home/solaraquarion/bluegriffon/src/path/client.mk:363: recipe for target 'configure' failed

**Comment by therealglazou** [comment]
W/o indication of machine / platform / OS / version, this is a totally useless bug report again.

**Comment by SolarAquarion** [comment]
ArchLinux

**Comment by muflone** [comment]
Hi 

I'm the maintainer of Bluegriffon in the official Arch Linux repositories.

You can find the 1.8 version in the community repository. If you need to build it again you can use the PKGBUILD+patches [1] or ABS in order to build the same binary package.

[1] https://projects.archlinux.org/svntogit/community.git/tree/trunk?h=packages/bluegriffon

**Comment by SolarAquarion** [comment]
@muflone i'm having a issue with the patches.  They're not working against current

**Comment by muflone** [comment]
Are you applying them against the 1.8 commit or against the latest source tree?
