### ISSUE TITLE
Unable to build 2.4.1 for 32 bit

### ISSUE THREAD

**Issue by muflone** [therealglazou/bluegriffon#49]
Hi

I'm unable to build BG 2.4.1 for x86 32 bit CPU.
The build process dies with the error:
```
 4:50.37 In file included from /build/bluegriffon/src/mozilla-central-c0d35b1c5ab5/bg/ipc/chromium/Unified_cpp_ipc_chromium0.cpp:110:0:
 4:50.37 /build/bluegriffon/src/mozilla-central-c0d35b1c5ab5/ipc/chromium/src/base/message_pump_libevent.cc:31:5: error: static assertion failed: bad EVENT__SIZEOF_OFF_T
 4:50.37      static_assert(EVENT__SIZEOF_##TYPE == sizeof(type), \
 4:50.37      ^
 4:50.37 /build/bluegriffon/src/mozilla-central-c0d35b1c5ab5/ipc/chromium/src/base/message_pump_libevent.cc:39:1: note: in expansion of macro ‘CHECK_EVENT_SIZEOF’
 4:50.37  CHECK_EVENT_SIZEOF(OFF_T,     off_t);
 4:50.37  ^~~~~~~~~~~~~~~~~~
 4:51.65 make[5]: *** [/build/bluegriffon/src/mozilla-central-c0d35b1c5ab5/config/rules.mk:1031: Unified_cpp_ipc_chromium0.o] Error 1
 4:51.65 make[4]: *** [/build/bluegriffon/src/mozilla-central-c0d35b1c5ab5/config/recurse.mk:73: ipc/chromium/target] Error 2
```

From the project home page it seems clear the 32 bit support was dropped. Does this mean that since 2.4.1 we cannot build BG anymore for 32 bit CPU?

**Comment by therealglazou** [comment]
Well. Mozilla says:

* for Linux "As of early 2015 it is no longer possible to do a full build of Firefox from source on most 32-bit systems; a 64-bit OS is required. "
* for Windows "You can still build 32-bit Firefox on a 64-bit Windows installation."
* for OS X, they say nothing so it could still work but I did not test it

**Comment by therealglazou** [comment]
Closing. https://github.com/therealglazou/bluegriffon/blob/master/config/mozconfig.win contains everything for w32 builds ; linux 32Bits remains unsupported.
