### ISSUE TITLE
BlueGriffon 2.4.1 defaults to <div> instead of <p> after heading

### ISSUE THREAD

**Issue by garretwilson** [therealglazou/bluegriffon#51]
I just upgraded to BlueGriffon 2.4.1 on Windows 10 Pro 64-bit. I'm editing an XHTML5 document:

```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" lang="en-US">
```

Whenever I'm editing a heading such as `<h1>foobar</h1>` and hit `Enter` at the end of the line, BlueGriffon 2.4.1 goes to the next line _and defaults to a new `<div>`_. The old (and correct) behavior was to default to a new `<p>`. It reduced productivity if I have to go change the `<div>` to a `<p>` every time I finish editing a heading and go to the next line using the `Enter` key.

Is this a bug, or is there some new setting that didn't get the correct default value?

**Comment by therealglazou** [comment]
Yes. Found it myself and already fixed it https://github.com/therealglazou/bluegriffon/commit/519216711825f5ca606e9049ac9ab6d3cf0400d1
