### ISSUE TITLE
Missing widgets for 2.4

### ISSUE THREAD

**Issue by muflone** [therealglazou/bluegriffon#52]
Hi

I'm trying to build BG 2.4 from sources and it builds fine (after applying [this patch](https://hg.mozilla.org/mozilla-central/raw-rev/4e9cd1d537cc)) but the application has a lot of drawing errors, missing widgets, resulting so totally unusable.

![schermata da 2017-11-04 17-24-16](https://user-images.githubusercontent.com/1284163/32407191-8fa365aa-c185-11e7-9d2d-95ffb9a6a185.png)

Attached mozconfig
[mozconfig.txt](https://github.com/therealglazou/bluegriffon/files/1443357/mozconfig.txt)

Until version 2.3 I was using the mozilla-central revision f14898695ee0 and applying [this patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1234158) all the content was properly rendered but now version 2.4 uses mozilla-central revision c0d35b1c5ab5 which is so different to apply the previous patch.

Can you share some hint to build BG 2.4 with gtk 3 support?

thank you

**Comment by therealglazou** [comment]
See https://github.com/therealglazou/bluegriffon/blob/master/config/mozconfig.ubuntu64

**Comment by muflone** [comment]
Unfortunately this doesn't fix my issues, I've recompiled it a lot of times but still a lot of missing UI elements.
