### ISSUE TITLE
feature request: auto reload

### ISSUE THREAD

**Issue by garretwilson** [therealglazou/bluegriffon#6]
Because of the various BlueGriffon bugs and shortcomings, I have to keep Atom editor loaded side-by-side with BG. When I make a change in BG, Atom immediately reflects the change! But when I make a change in Atom... BG just sits there and does nothing. There is no File > Reload, and F5 does not work.

This is not covered by http://bugzilla.bluegriffon.org/show_bug.cgi?id=325 .

**Comment by garretwilson** [comment]
This seems related, but was marked as invalid:

http://bugzilla.bluegriffon.org/show_bug.cgi?id=594

This is not invalid! I don't want to right-click on a tab every time I make changes externally. I want BG to recognize that the file was changed and reload it. At the very least there should be a key mapping for this, but really that isn't ideal.

**Comment by therealglazou** [comment]
Done in commit 7c2fa505046664921a34733176ab3a2146ecb58b in bg2 branch

**Comment by garretwilson** [comment]
Yay! Exciting to see movement on bugs. Are there nightly builds, or at least a new alpha/beta release scheduled soon?
