### ISSUE TITLE
Version 3.1 crashes when pasting copied image

### ISSUE THREAD

**Issue by heklaz** [therealglazou/bluegriffon#73]
BlueGriffon version 3.1 crashes when trying to paste an image copied from Safari (as "Copy Image")
This used to work previous version.

URL of image src is https if that matters.

MacOS 10.14.6

**Comment by therealglazou** [comment]
Confirming the bug and investigating. Thanks for the report, @heklaz .

**Comment by therealglazou** [comment]
Fix in hand

**Comment by therealglazou** [comment]
Fixed by commit 78dff7c42cf9e6d54a02925cc152c6f6be517aed

**Comment by vehosah** [comment]
> 
> 
> Fixed by commit [78dff7c](https://github.com/therealglazou/bluegriffon/commit/78dff7c42cf9e6d54a02925cc152c6f6be517aed)

when will we have a new update?
