### ISSUE TITLE
BlueGriffon breaks Font Awesome

### ISSUE THREAD

**Issue by garretwilson** [therealglazou/bluegriffon#8]
I want to embed a Font Awesome symbol in my HTML. See these examples: https://fortawesome.github.io/Font-Awesome/examples/

So I go into source code mode in GB and enter:

    <i class="fa fa-camera-retro"></i>

When I go back into WYSIWYG mode, BG deletes the entire tag. (Yes, `<i>` is now valid in HTML5.)

**Comment by garretwilson** [comment]
BG allows me to use `<span>`. It has something personal against `<i>`, I suppose. (I used to as well, before HTML5 rehabilitated it.) Still, BG shouldn't be imposing its personal feelings on which tags I use if I specifically choose one.

**Comment by therealglazou** [comment]
That's already fixed in 2.0. `<b>`, `<i>` and `<u>` are now correctly handled.

**Comment by garretwilson** [comment]
Since this is "already fixed in 2.0", is there a Windows installer for 2.0 I'm missing somewhere?

Maybe you meant "that will be fixed in 2.0, some day in the future". But it still isn't fixed in my day-to-day work unfortunately. :frowning: 

Have you considered releasing a 1.8.1 version with all these fixes you say are addressed in 2.0? That sure would help some of us---or at least me.
